In [11]:
import numpy as np
from tqdm import tqdm


environment = np.array([
    [0, 0, 0, 1],
    [0, 1, 0, 1],
    [0, 1, 0, 2],
    [0, 0, 0, 1]
])

gamma = 0.8
epsilon = 0.1
learning_rate = 0.9

q_table = np.zeros((4, 4))

def choose_action(state):
    if np.random.uniform(0, 1) < epsilon:
        return np.random.choice([0, 1, 2, 3])  # Actions: haut, bas, gauche, droite
    else:
        return np.argmax(q_table[state])

def update_q_table(state, action, reward, next_state):
    q_predict = q_table[state, action]
    q_target = reward + gamma * np.max(q_table[next_state])
    q_table[state, action] += learning_rate * (q_target - q_predict)

for episode in tqdm(range(200), desc='Training'):
    state = (0, 0)
    while True:
        action = choose_action(state)
        next_state = (state[0] + [-1, 1, 0, 0][action], state[1] + [0, 0, -1, 1][action])
        next_state = (max(0, min(next_state[0], environment.shape[0]-1)), max(0, min(next_state[1], environment.shape[1]-1)))
        reward = -1 if environment[next_state] == 0 else 10 if environment[next_state] == 2 else -100
        update_q_table(state, action, reward, next_state)
        state = next_state
        if environment[state] == 2:
            break

print("Table Q:")
print(q_table)

Training:   0%|          | 0/200 [00:00<?, ?it/s]

Training: 100%|██████████| 200/200 [01:00<00:00,  3.32it/s]

Table Q:
[[-472.26996053 -240.89845611 -112.27439679 -465.33821153]
 [-466.10848456 -350.80603789 -121.07732811 -176.12307014]
 [ -92.7033605   -29.17787555 -250.21429019 -453.27947237]
 [-472.26996053 -341.45106572 -112.2510292  -464.40753859]]


In [16]:
# Affichage des actions pour chaque état final
print("Actions pour chaque état final:")
for i in range(environment.shape[0]):
    for j in range(environment.shape[1]):
        if environment[i, j] == 2:
            print(f"État ({i}, {j}):")
            for action, action_name in enumerate(["Aller en haut", "Aller en bas", "Aller à gauche", "Aller à droite"]):
                print(f"   {action_name}: Q-value = {q_table[i, j]}")

Actions pour chaque état final:
État (2, 3):
   Aller en haut: Q-value = -453.2794723695845
   Aller en bas: Q-value = -453.2794723695845
   Aller à gauche: Q-value = -453.2794723695845
   Aller à droite: Q-value = -453.2794723695845


In [17]:
import numpy as np
from tqdm import tqdm


environment = np.array([
    [0, 0, 0, 1],
    [0, 1, 0, 1],
    [0, 1, 0, 2],
    [0, 0, 0, 1]
])

gamma = 0.8
epsilon = 0.1
learning_rate = 0.9

q_table = np.zeros((4, 4))

def choose_action(state):
    if np.random.uniform(0, 1) < epsilon:
        return np.random.choice([0, 1, 2, 3])  # Actions: haut, bas, gauche, droite
    else:
        return np.argmax(q_table[state])

def update_q_table(state, action, reward, next_state):
    q_predict = q_table[state, action]
    q_target = reward + gamma * np.max(q_table[next_state])
    q_table[state, action] += learning_rate * (q_target - q_predict)

for episode in tqdm(range(500), desc='Training'):
    state = (0, 0)
    while True:
        action = choose_action(state)
        next_state = (state[0] + [-1, 1, 0, 0][action], state[1] + [0, 0, -1, 1][action])
        next_state = (max(0, min(next_state[0], environment.shape[0]-1)), max(0, min(next_state[1], environment.shape[1]-1)))
        reward = -1 if environment[next_state] == 0 else 10 if environment[next_state] == 2 else -100
        update_q_table(state, action, reward, next_state)
        state = next_state
        if environment[state] == 2:
            break

print("Table Q:")
print(q_table)

Training: 100%|██████████| 500/500 [02:21<00:00,  3.54it/s]

Table Q:
[[-433.66617114 -122.59617277   -5.05893407 -417.0832497 ]
 [-328.17112923 -340.65901051   -7.42733816  -23.62195854]
 [  -5.04714726 -207.18611367 -157.68902775 -417.08315029]
 [-433.6665852  -303.32303942   -5.05910201 -230.45476975]]


In [18]:
# Affichage des actions pour chaque état final
print("Actions pour chaque état final:")
for i in range(environment.shape[0]):
    for j in range(environment.shape[1]):
        if environment[i, j] == 2:
            print(f"État ({i}, {j}):")
            for action, action_name in enumerate(["Aller en haut", "Aller en bas", "Aller à gauche", "Aller à droite"]):
                print(f"   {action_name}: Q-value = {q_table[i, j]}")

Actions pour chaque état final:
État (2, 3):
   Aller en haut: Q-value = -417.0831502925515
   Aller en bas: Q-value = -417.0831502925515
   Aller à gauche: Q-value = -417.0831502925515
   Aller à droite: Q-value = -417.0831502925515


In [19]:
import numpy as np
from tqdm import tqdm


environment = np.array([
    [0, 0, 0, 1],
    [0, 1, 0, 1],
    [0, 1, 0, 2],
    [0, 0, 0, 1]
])

gamma = 0.8
epsilon = 0.1
learning_rate = 0.9

q_table = np.zeros((4, 4))

def choose_action(state):
    if np.random.uniform(0, 1) < epsilon:
        return np.random.choice([0, 1, 2, 3])  # Actions: haut, bas, gauche, droite
    else:
        return np.argmax(q_table[state])

def update_q_table(state, action, reward, next_state):
    q_predict = q_table[state, action]
    q_target = reward + gamma * np.max(q_table[next_state])
    q_table[state, action] += learning_rate * (q_target - q_predict)

for episode in tqdm(range(1000), desc='Training'):
    state = (0, 0)
    while True:
        action = choose_action(state)
        next_state = (state[0] + [-1, 1, 0, 0][action], state[1] + [0, 0, -1, 1][action])
        next_state = (max(0, min(next_state[0], environment.shape[0]-1)), max(0, min(next_state[1], environment.shape[1]-1)))
        reward = -1 if environment[next_state] == 0 else 10 if environment[next_state] == 2 else -100
        update_q_table(state, action, reward, next_state)
        state = next_state
        if environment[state] == 2:
            break

print("Table Q:")
print(q_table)

Training: 100%|██████████| 1000/1000 [04:49<00:00,  3.46it/s]

Table Q:
[[-458.18759359 -104.98705979   -5.58425003 -447.84896986]
 [-439.13776325 -335.57453765   -7.7454857    -6.35618543]
 [  -5.46740002   -7.19640277  -18.51728988 -420.32614464]
 [-458.18759359 -304.15716748   -5.58423511 -447.61391517]]


In [20]:
# Affichage des actions pour chaque état final
print("Actions pour chaque état final:")
for i in range(environment.shape[0]):
    for j in range(environment.shape[1]):
        if environment[i, j] == 2:
            print(f"État ({i}, {j}):")
            for action, action_name in enumerate(["Aller en haut", "Aller en bas", "Aller à gauche", "Aller à droite"]):
                print(f"   {action_name}: Q-value = {q_table[i, j]}")

Actions pour chaque état final:
État (2, 3):
   Aller en haut: Q-value = -420.3261446406493
   Aller en bas: Q-value = -420.3261446406493
   Aller à gauche: Q-value = -420.3261446406493
   Aller à droite: Q-value = -420.3261446406493
